<section class="content-card recovery-heading" id="topo-recuperacao">
    <div class="section-head"><div><span class="eyebrow">Somente Administrador Master</span><h1>Exclusão de dados de teste</h1><p class="muted">Consulte somente as últimas inserções no banco e inclusões de documentos no repositório.</p></div><a class="btn btn-secondary" href="<?php echo e(url('/admin')); ?>">Voltar à área administrativa</a></div>
</section>
<section class="content-card recovery-risk" role="alert">
    <h2>⚠ Risco de perda e inconsistência de dados</h2>
    <p>Uma exclusão direta pode quebrar agendamentos, inscrições, certificados, vínculos de pessoas e arquivos. Faça backup completo antes de qualquer intervenção fora desta página.</p>
    <p><strong>Regra geral:</strong> o sistema inativa ou cancela e mantém o histórico. <strong>Atestados e certificados:</strong> o registro é excluído do banco na mesma operação em que seus documentos são enviados para a quarentena recuperável.</p>
</section>
<section class="content-card"><form method="GET" action="<?php echo e(url('/admin-recuperacao-dados')); ?>" class="recovery-filter"><label>Buscar<input type="search" name="busca" value="<?php echo e($search); ?>" placeholder="Evento, entidade, ID, nome, CPF ou arquivo"></label><label>Quantidade<input type="number" name="limite" min="1" max="50" value="<?php echo e((string) $limit); ?>"></label><button class="btn btn-primary" type="submit">Atualizar listas</button></form></section>
<section class="content-card top-gap"><div class="section-head"><div><h2>Últimas inserções no sistema</h2><p class="muted">São mostradas no máximo 50 inserções ainda não excluídas ou revertidas. Atualizações de dados não aparecem nesta página.</p></div><a class="btn btn-secondary" href="#operacoes-revertidas" data-scroll-reverted>Inserções já revertidas</a></div><p class="notice notice-warning"><strong>Revisão manual necessária</strong> significa que a inserção possui dependências que impedem uma exclusão automática segura. Nesses casos, esta página apenas apresenta as informações e não executa alterações.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Tipo de inserção</th><th>Entidade / ID</th><th>Responsável</th><th>Segurança</th><th>Ação</th></tr></thead><tbody>
<?php if (empty($operations)) { ?><tr><td colspan="6">Nenhuma operação encontrada.</td></tr><?php } ?>
<?php foreach ($operations as $operation) { ?><tr data-recovery-operation-row="<?php echo e((string) $operation['id']); ?>"><td><?php echo e((string) $operation['created_at']); ?></td><td><strong><?php echo e((string) $operation['operation_kind']); ?></strong><br><small><?php echo e((string) $operation['tipo_evento']); ?></small></td><td><?php echo e((string) $operation['tipo_entidade']); ?> #<?php echo e((string) ($operation['entidade_id'] ?? '-')); ?></td><td><?php echo e((string) ($operation['autor_nome'] ?? 'Sistema')); ?></td><td><?php echo !empty($operation['reversed']) ? 'Já revertida' : e((string) $operation['risk_label']); ?></td><td><button type="button" class="btn btn-secondary recovery-details-button" data-log-id="<?php echo e((string) $operation['id']); ?>">Ver informações</button></td></tr><?php } ?>
</tbody></table></div></section>
<section class="content-card top-gap" id="operacoes-revertidas" tabindex="-1">
    <div class="section-head"><div><h2>Inserções revertidas</h2><p class="muted">Histórico das últimas inserções que já foram excluídas ou revertidas. Não é possível executar a operação novamente.</p></div><a class="btn btn-secondary" href="#topo-recuperacao" data-scroll-top>Voltar para cima</a></div>
    <div class="table-wrap"><table class="data-table"><thead><tr><th>Operação original</th><th>Entidade / ID</th><th>Responsável</th><th>Revertida em</th><th>Situação</th><th>Informações</th></tr></thead><tbody>
    <?php if (empty($revertedOperations)) { ?><tr><td colspan="6">Nenhuma operação revertida encontrada.</td></tr><?php } ?>
    <?php foreach ($revertedOperations as $operation) { ?><tr><td><strong><?php echo e((string) $operation['operation_kind']); ?></strong><br><small><?php echo e((string) $operation['tipo_evento']); ?></small></td><td><?php echo e((string) $operation['tipo_entidade']); ?> #<?php echo e((string) ($operation['entidade_id'] ?? '-')); ?></td><td><?php echo e((string) ($operation['autor_nome'] ?? 'Sistema')); ?></td><td><?php echo e((string) ($operation['revertido_em'] ?? '-')); ?></td><td>Revertida — nenhuma nova reversão permitida</td><td><button type="button" class="btn btn-secondary recovery-details-button" data-log-id="<?php echo e((string) $operation['id']); ?>">Ver informações</button></td></tr><?php } ?>
    </tbody></table></div>
</section>
<div id="recovery-modal" class="popup-overlay hidden" aria-hidden="true"><div class="popup-card recovery-modal-card" role="dialog" aria-modal="true" aria-labelledby="recovery-modal-title" onclick="event.stopPropagation()"><button type="button" class="popup-close-icon" data-close-popup="#recovery-modal" data-recovery-close aria-label="Fechar" onclick="var modal=document.getElementById('recovery-modal'); if(modal){modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');} return false;">&times;</button><div class="popup-head"><h3 id="recovery-modal-title">Informações da inserção</h3></div><div class="popup-body" id="recovery-modal-body"></div><form class="stack-form hidden" id="recovery-action-form"><input type="hidden" name="log_id" id="recovery-log-id"><label>Motivo da exclusão<textarea name="motivo" minlength="10" required></textarea></label><label>Digite <strong>EXCLUIR</strong> para confirmar<input name="confirmacao" autocomplete="off" required></label><p class="form-error hidden" id="recovery-form-error"></p><div class="popup-actions"><button type="button" class="btn btn-secondary" data-close-popup="#recovery-modal" data-recovery-close onclick="var modal=document.getElementById('recovery-modal'); if(modal){modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');} return false;">Cancelar</button><button type="submit" class="btn btn-danger" id="recovery-submit-button">Excluir registro inserido</button></div></form></div></div>
<script src="<?php echo e(asset_url('js/data-recovery.js')); ?>"></script>
