USE cursos_esportivos_sbc;

CREATE TABLE IF NOT EXISTS home_quadros_informativos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    titulo VARCHAR(70) NOT NULL,
    paragrafo_1 VARCHAR(110) NULL,
    paragrafo_1_link_rotulo VARCHAR(40) NULL,
    paragrafo_1_link_url VARCHAR(255) NULL,
    paragrafo_2 VARCHAR(110) NULL,
    paragrafo_2_link_rotulo VARCHAR(40) NULL,
    paragrafo_2_link_url VARCHAR(255) NULL,
    paragrafo_3 VARCHAR(110) NULL,
    paragrafo_3_link_rotulo VARCHAR(40) NULL,
    paragrafo_3_link_url VARCHAR(255) NULL,
    paragrafo_4 VARCHAR(110) NULL,
    paragrafo_4_link_rotulo VARCHAR(40) NULL,
    paragrafo_4_link_url VARCHAR(255) NULL,
    paragrafo_5 VARCHAR(110) NULL,
    paragrafo_5_link_rotulo VARCHAR(40) NULL,
    paragrafo_5_link_url VARCHAR(255) NULL,
    atualizado_por_conta_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_home_quadro_conta FOREIGN KEY (atualizado_por_conta_id) REFERENCES contas(id)
) ENGINE=InnoDB;

INSERT INTO home_quadros_informativos (
    slug, titulo,
    paragrafo_1, paragrafo_1_link_rotulo, paragrafo_1_link_url,
    paragrafo_2, paragrafo_2_link_rotulo, paragrafo_2_link_url,
    paragrafo_3, paragrafo_3_link_rotulo, paragrafo_3_link_url,
    paragrafo_4, paragrafo_4_link_rotulo, paragrafo_4_link_url,
    paragrafo_5, paragrafo_5_link_rotulo, paragrafo_5_link_url,
    atualizado_por_conta_id, updated_at
) VALUES (
    'home-o-que-precisa-saber',
    'O que voce precisa saber:',
    'O cadastro no sistema so pode ser feito por um responsavel maior de idade.',
    NULL,
    NULL,
    'Agendamentos de treinos e inscricoes para cursos esportivos sao gratuitos.',
    NULL,
    NULL,
    'Dependentes podem ter transferencia definitiva de responsavel registrada no sistema.',
    NULL,
    NULL,
    'As vagas para treinos e turmas sao limitadas e seguem disponibilidade.',
    NULL,
    NULL,
    'A base do sistema ja esta pronta para certificados, atestados e inscricoes por temporada.',
    NULL,
    NULL,
    1,
    NOW()
)
ON DUPLICATE KEY UPDATE
    titulo = VALUES(titulo),
    paragrafo_1 = VALUES(paragrafo_1),
    paragrafo_1_link_rotulo = VALUES(paragrafo_1_link_rotulo),
    paragrafo_1_link_url = VALUES(paragrafo_1_link_url),
    paragrafo_2 = VALUES(paragrafo_2),
    paragrafo_2_link_rotulo = VALUES(paragrafo_2_link_rotulo),
    paragrafo_2_link_url = VALUES(paragrafo_2_link_url),
    paragrafo_3 = VALUES(paragrafo_3),
    paragrafo_3_link_rotulo = VALUES(paragrafo_3_link_rotulo),
    paragrafo_3_link_url = VALUES(paragrafo_3_link_url),
    paragrafo_4 = VALUES(paragrafo_4),
    paragrafo_4_link_rotulo = VALUES(paragrafo_4_link_rotulo),
    paragrafo_4_link_url = VALUES(paragrafo_4_link_url),
    paragrafo_5 = VALUES(paragrafo_5),
    paragrafo_5_link_rotulo = VALUES(paragrafo_5_link_rotulo),
    paragrafo_5_link_url = VALUES(paragrafo_5_link_url),
    atualizado_por_conta_id = VALUES(atualizado_por_conta_id),
    updated_at = NOW();
