CREATE TABLE IF NOT EXISTS rematriculas (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    destino_turma_id BIGINT UNSIGNED NOT NULL,
    origem_tipo ENUM('current', 'legacy') NOT NULL,
    origem_temporada_id BIGINT UNSIGNED NOT NULL,
    origem_local_id BIGINT UNSIGNED NOT NULL,
    origem_modalidade_id BIGINT UNSIGNED NOT NULL,
    origem_turma_id BIGINT UNSIGNED NOT NULL,
    origem_temporada_nome VARCHAR(150) NOT NULL,
    origem_local_nome VARCHAR(180) NOT NULL,
    origem_modalidade_nome VARCHAR(150) NOT NULL,
    origem_turma_nome VARCHAR(180) NOT NULL,
    prazo_dias TINYINT UNSIGNED NOT NULL,
    prazo_final DATETIME NOT NULL,
    status ENUM('ativa', 'encerrada', 'cancelada') NOT NULL DEFAULT 'ativa',
    criado_por_conta_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    INDEX idx_rematricula_destino (destino_turma_id, status),
    INDEX idx_rematricula_origem (origem_tipo, origem_temporada_id, origem_turma_id),
    CONSTRAINT fk_rematricula_destino FOREIGN KEY (destino_turma_id) REFERENCES turmas(id) ON DELETE CASCADE,
    CONSTRAINT fk_rematricula_autor FOREIGN KEY (criado_por_conta_id) REFERENCES contas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rematricula_convites (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rematricula_id BIGINT UNSIGNED NOT NULL,
    origem_pessoa_id BIGINT UNSIGNED NULL,
    pessoa_id BIGINT UNSIGNED NULL,
    pessoa_nome VARCHAR(180) NOT NULL,
    pessoa_cpf CHAR(11) NOT NULL,
    pessoa_data_nascimento DATE NULL,
    publico_alvo ENUM('geral', 'pcd', 'plm', 'pvs') NOT NULL DEFAULT 'geral',
    responsavel_conta_id BIGINT UNSIGNED NULL,
    notificacao_id BIGINT UNSIGNED NULL,
    notificacao_destinatario_id BIGINT UNSIGNED NULL,
    token_id BIGINT UNSIGNED NULL,
    status ENUM('nao_enviada', 'aguardando_resposta', 'recusada', 'token_gerado', 'inscrita', 'sem_responsavel') NOT NULL DEFAULT 'nao_enviada',
    enviado_em DATETIME NULL,
    respondido_em DATETIME NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_rematricula_pessoa (rematricula_id, pessoa_cpf),
    INDEX idx_rematricula_convite_status (rematricula_id, status),
    INDEX idx_rematricula_convite_responsavel (responsavel_conta_id, status),
    CONSTRAINT fk_rematricula_convite_campanha FOREIGN KEY (rematricula_id) REFERENCES rematriculas(id) ON DELETE CASCADE,
    CONSTRAINT fk_rematricula_convite_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoas(id) ON DELETE SET NULL,
    CONSTRAINT fk_rematricula_convite_responsavel FOREIGN KEY (responsavel_conta_id) REFERENCES contas(id) ON DELETE SET NULL,
    CONSTRAINT fk_rematricula_convite_notificacao FOREIGN KEY (notificacao_id) REFERENCES notificacoes(id) ON DELETE SET NULL,
    CONSTRAINT fk_rematricula_convite_destinatario FOREIGN KEY (notificacao_destinatario_id) REFERENCES notificacoes_destinatarios(id) ON DELETE SET NULL,
    CONSTRAINT fk_rematricula_convite_token FOREIGN KEY (token_id) REFERENCES tokens_inscricao_turma(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rematricula_convites_historico (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    convite_id BIGINT UNSIGNED NOT NULL,
    status_anterior VARCHAR(40) NOT NULL,
    status_novo VARCHAR(40) NOT NULL,
    observacao VARCHAR(255) NULL,
    realizado_por_conta_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_rematricula_historico (convite_id, created_at),
    CONSTRAINT fk_rematricula_historico_convite FOREIGN KEY (convite_id) REFERENCES rematricula_convites(id) ON DELETE CASCADE,
    CONSTRAINT fk_rematricula_historico_conta FOREIGN KEY (realizado_por_conta_id) REFERENCES contas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
