USE cursos_esportivos_sbc;

CREATE TABLE IF NOT EXISTS cadastros_externos_migracao (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_externo BIGINT UNSIGNED NOT NULL,
    cpf CHAR(11) NOT NULL,
    nome_completo VARCHAR(180) NOT NULL,
    data_nascimento DATE NULL,
    sexo VARCHAR(40) NULL,
    telefone_whatsapp VARCHAR(30) NULL,
    email VARCHAR(180) NULL,
    numero_cartao_sus VARCHAR(30) NULL,
    cep VARCHAR(10) NULL,
    logradouro VARCHAR(180) NULL,
    numero_endereco VARCHAR(30) NULL,
    complemento VARCHAR(120) NULL,
    bairro VARCHAR(120) NULL,
    cidade VARCHAR(120) NULL,
    uf CHAR(2) NULL,
    contato_emergencia_nome VARCHAR(180) NULL,
    contato_emergencia_telefone VARCHAR(30) NULL,
    responsavel1_nome VARCHAR(180) NULL,
    responsavel1_cpf CHAR(11) NULL,
    responsavel2_nome VARCHAR(180) NULL,
    responsavel2_cpf CHAR(11) NULL,
    situacao_origem VARCHAR(80) NULL,
    data_inclusao_origem DATETIME NULL,
    data_alteracao_origem DATETIME NULL,
    status_migracao VARCHAR(20) NOT NULL DEFAULT 'pendente',
    pessoa_id BIGINT UNSIGNED NULL,
    importado_por_conta_id BIGINT UNSIGNED NULL,
    importado_em DATETIME NOT NULL,
    migrado_em DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_cadastros_externos_id (id_externo),
    INDEX idx_cadastros_externos_cpf_status (cpf, status_migracao),
    INDEX idx_cadastros_externos_nome (nome_completo),
    INDEX idx_cadastros_externos_status (status_migracao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
