<?php

use App\Controllers\AdminController;
use App\Controllers\AgendaController;
use App\Controllers\BlogController;
use App\Controllers\CepController;
use App\Controllers\AuthController;
use App\Controllers\DashboardController;
use App\Controllers\HomeController;
use App\Controllers\ProfileController;

return [
    ['GET', '/', [HomeController::class, 'index']],
    ['GET', '/blog', [BlogController::class, 'index']],
    ['GET', '/blog/post', [BlogController::class, 'post']],
    ['GET', '/login', [AuthController::class, 'showLogin']],
    ['POST', '/login', [AuthController::class, 'login']],
    ['GET', '/cadastro', [AuthController::class, 'showRegister']],
    ['POST', '/cadastro', [AuthController::class, 'register']],
    ['GET', '/api/cpf/cadastro-status', [AuthController::class, 'checkRegisterCpf']],
    ['POST', '/logout', [AuthController::class, 'logout']],
    ['GET', '/perfil/completar', [ProfileController::class, 'showComplete']],
    ['POST', '/perfil/completar', [ProfileController::class, 'complete']],
    ['GET', '/dashboard', [DashboardController::class, 'index']],
    ['GET', '/perfil/certificados/modal', [ProfileController::class, 'certificateModal']],
    ['GET', '/perfil/certificados/arquivo', [ProfileController::class, 'certificateDocument']],
    ['POST', '/perfil/certificados/salvar', [ProfileController::class, 'saveCertificateDocuments']],
    ['GET', '/perfil/atestados/modal', [ProfileController::class, 'healthCertificatesModal']],
    ['POST', '/perfil/atestados/salvar', [ProfileController::class, 'saveHealthCertificates']],
    ['GET', '/dependentes/detalhe', [ProfileController::class, 'dependentDetails']],
    ['POST', '/dependentes/salvar', [ProfileController::class, 'saveDependent']],
    ['POST', '/dependentes/atualizar', [ProfileController::class, 'updateDependent']],
    ['POST', '/dependentes/transferir', [ProfileController::class, 'transferDependent']],
    ['GET', '/agenda', [AgendaController::class, 'index']],
    ['GET', '/agenda/pessoas', [AgendaController::class, 'schedulablePeople']],
    ['GET', '/agenda/elegibilidade', [AgendaController::class, 'scheduleEligibility']],
    ['GET', '/api/agenda/eventos', [AgendaController::class, 'events']],
    ['GET', '/api/ceps/validar', [CepController::class, 'validate']],
    ['POST', '/agenda/agendar', [AgendaController::class, 'book']],
    ['POST', '/agenda/horarios-especiais/inscrever', [AgendaController::class, 'registerSpecialSchedule']],
    ['POST', '/agenda/eventos-especiais/inscrever', [AgendaController::class, 'registerSpecialSchedule']],
    ['POST', '/agenda/cancelar', [AgendaController::class, 'cancel']],
    ['GET', '/admin', [AdminController::class, 'index']],
    ['GET', '/admin/secao', [AdminController::class, 'section']],
    ['GET', '/admin/pessoas/detalhe', [AdminController::class, 'personDetails']],
    ['GET', '/admin/pessoas/lista', [AdminController::class, 'peoplePanel']],
    ['GET', '/admin/usuarios/detalhe', [AdminController::class, 'userDetails']],
    ['GET', '/admin/usuarios/dependentes', [AdminController::class, 'userDependents']],
    ['POST', '/admin/usuarios/papeis', [AdminController::class, 'updateUserRoles']],
    ['GET', '/admin/postagens/detalhe', [AdminController::class, 'postDetails']],
    ['GET', '/admin/certificados/arquivo', [AdminController::class, 'certificateDocument']],
    ['GET', '/admin/certificados/validacao/modal', [AdminController::class, 'conditionValidationModal']],
    ['GET', '/admin/atestados/validacao/modal', [AdminController::class, 'healthCertificateValidationModal']],
    ['GET', '/api/admin/agenda/eventos', [AdminController::class, 'calendarEvents']],
    ['GET', '/admin/agendamentos/ocorrencia', [AdminController::class, 'bookingOccurrence']],
    ['GET', '/admin/horarios-semanais/detalhe', [AdminController::class, 'weeklyScheduleDetails']],
    ['GET', '/admin/agenda-horarios-especiais/detalhe', [AdminController::class, 'specialScheduleDetails']],
    ['GET', '/admin/agenda-eventos-especiais/detalhe', [AdminController::class, 'specialScheduleDetails']],
    ['POST', '/admin/pessoas/atualizar', [AdminController::class, 'updatePerson']],
    ['POST', '/admin/agendamentos/presenca', [AdminController::class, 'markBookingAttendance']],
    ['POST', '/admin/certificados/validacao/salvar', [AdminController::class, 'saveConditionValidation']],
    ['POST', '/admin/atestados/validacao/salvar', [AdminController::class, 'saveHealthCertificateValidation']],
    ['POST', '/admin/espacos/suspensoes', [AdminController::class, 'storeSpaceSuspension']],
    ['POST', '/admin/espacos/suspensoes/inativar', [AdminController::class, 'deactivateSpaceSuspension']],
    ['POST', '/admin/horarios-semanais', [AdminController::class, 'storeWeeklySchedule']],
    ['POST', '/admin/horarios-semanais/atualizar', [AdminController::class, 'updateWeeklySchedule']],
    ['POST', '/admin/horarios-semanais/inativar', [AdminController::class, 'deactivateWeeklySchedule']],
    ['POST', '/admin/horarios-semanais/ativar', [AdminController::class, 'activateWeeklySchedule']],
    ['POST', '/admin/agenda-horarios-especiais', [AdminController::class, 'storeSpecialSchedule']],
    ['POST', '/admin/agenda-horarios-especiais/atualizar', [AdminController::class, 'updateSpecialSchedule']],
    ['POST', '/admin/agenda-horarios-especiais/inativar', [AdminController::class, 'deactivateSpecialSchedule']],
    ['POST', '/admin/agenda-eventos-especiais', [AdminController::class, 'storeSpecialSchedule']],
    ['POST', '/admin/agenda-eventos-especiais/atualizar', [AdminController::class, 'updateSpecialSchedule']],
    ['POST', '/admin/agenda-eventos-especiais/inativar', [AdminController::class, 'deactivateSpecialSchedule']],
    ['POST', '/admin/home-info', [AdminController::class, 'saveHomeInfoBox']],
    ['POST', '/admin/comunicacao-oficial', [AdminController::class, 'saveOfficialCommunication']],
    ['POST', '/admin/postagens', [AdminController::class, 'storePost']],
    ['POST', '/admin/postagens/remover', [AdminController::class, 'deletePost']],
    ['POST', '/admin/site-popups', [AdminController::class, 'storeSitePopup']],
    ['POST', '/admin/site-popups/status', [AdminController::class, 'updateSitePopupStatus']],
    ['POST', '/admin/site-popups/remover', [AdminController::class, 'deleteSitePopup']],
    ['POST', '/admin/ceps-excecao', [AdminController::class, 'storeCepException']],
    ['POST', '/admin/ceps-excecao/remover', [AdminController::class, 'deleteCepException']],
    ['POST', '/admin/ceps-intervalo', [AdminController::class, 'storeAcceptedRange']],
    ['POST', '/admin/ceps-intervalo/remover', [AdminController::class, 'deleteAcceptedRange']],
];
