<?php

use App\Controllers\AdminController;
use App\Controllers\AgendaController;
use App\Controllers\BlogController;
use App\Controllers\CepController;
use App\Controllers\AuthController;
use App\Controllers\DashboardController;
use App\Controllers\ErrorController;
use App\Controllers\HomeController;
use App\Controllers\ProfileController;
use App\Controllers\DataRecoveryController;
use App\Controllers\ProfessorController;

return [
    ['GET', '/', [HomeController::class, 'index']],
    ['GET', '/teste-erros', [ErrorController::class, 'testCenter']],
    ['GET', '/teste_erros', [ErrorController::class, 'testCenter']],
    ['GET', '/blog', [BlogController::class, 'index']],
    ['GET', '/blog/post', [BlogController::class, 'post']],
    ['GET', '/login', [AuthController::class, 'showLogin']],
    ['POST', '/login', [AuthController::class, 'login']],
    ['GET', '/cadastro', [AuthController::class, 'showRegister']],
    ['POST', '/cadastro', [AuthController::class, 'register']],
    ['GET', '/api/cpf/cadastro-status', [AuthController::class, 'checkRegisterCpf']],
    ['POST', '/logout', [AuthController::class, 'logout']],
    ['GET', '/perfil/completar', [ProfileController::class, 'showComplete']],
    ['POST', '/perfil/completar', [ProfileController::class, 'complete']],
    ['GET', '/api/pessoas-externas/registros', [ProfileController::class, 'externalPersonRecords']],
    ['GET', '/api/pessoas-externas/registro', [ProfileController::class, 'externalPersonSelected']],
    ['GET', '/dashboard', [DashboardController::class, 'index']],
    ['GET', '/perfil/certificados/modal', [ProfileController::class, 'certificateModal']],
    ['GET', '/perfil/certificados/arquivo', [ProfileController::class, 'certificateDocument']],
    ['POST', '/perfil/certificados/salvar', [ProfileController::class, 'saveCertificateDocuments']],
    ['GET', '/perfil/atestados/modal', [ProfileController::class, 'healthCertificatesModal']],
    ['POST', '/perfil/atestados/salvar', [ProfileController::class, 'saveHealthCertificates']],
    ['GET', '/dependentes/detalhe', [ProfileController::class, 'dependentDetails']],
    ['POST', '/dependentes/salvar', [ProfileController::class, 'saveDependent']],
    ['POST', '/dependentes/atualizar', [ProfileController::class, 'updateDependent']],
    ['POST', '/dependentes/transferir', [ProfileController::class, 'transferDependent']],
    ['GET', '/agenda', [AgendaController::class, 'index']],
    ['GET', '/agenda/pessoas', [AgendaController::class, 'schedulablePeople']],
    ['GET', '/agenda/elegibilidade', [AgendaController::class, 'scheduleEligibility']],
    ['GET', '/api/agenda/eventos', [AgendaController::class, 'events']],
    ['GET', '/api/ceps/validar', [CepController::class, 'validate']],
    ['GET', '/api/ceps/endereco', [CepController::class, 'address']],
    ['POST', '/agenda/agendar', [AgendaController::class, 'book']],
    ['POST', '/agenda/horarios-especiais/inscrever', [AgendaController::class, 'registerSpecialSchedule']],
    ['POST', '/agenda/cancelar', [AgendaController::class, 'cancel']],
    ['GET', '/admin', [AdminController::class, 'index']],
    ['GET', '/admin-recuperacao-dados', [DataRecoveryController::class, 'index']],
    ['GET', '/admin/recuperacao-dados/detalhe', [DataRecoveryController::class, 'details']],
    ['POST', '/admin/recuperacao-dados/reverter', [DataRecoveryController::class, 'reverse']],
    ['GET', '/admin/secao', [AdminController::class, 'section']],
    ['GET', '/admin/pessoas/detalhe', [AdminController::class, 'personDetails']],
    ['GET', '/admin/pessoas/lista', [AdminController::class, 'peoplePanel']],
    ['GET', '/admin/migracao-cadastros/lista', [AdminController::class, 'externalMigrationPanel']],
    ['GET', '/admin/migracao-cadastros/detalhe', [AdminController::class, 'externalMigrationDetails']],
    ['POST', '/admin/migracao-cadastros/importar', [AdminController::class, 'importExternalMigration']],
    ['POST', '/admin/migracao-atestados/importar', [AdminController::class, 'importExternalHealthCertificates']],
    ['POST', '/admin/migracao-cadastros/remover', [AdminController::class, 'deleteExternalMigration']],
    ['GET', '/admin/usuarios/detalhe', [AdminController::class, 'userDetails']],
    ['GET', '/admin/usuarios/dependentes', [AdminController::class, 'userDependents']],
    ['POST', '/admin/usuarios/papeis', [AdminController::class, 'updateUserRoles']],
    ['GET', '/admin/postagens/detalhe', [AdminController::class, 'postDetails']],
    ['GET', '/admin/certificados/arquivo', [AdminController::class, 'certificateDocument']],
    ['GET', '/admin/certificados/validacao/modal', [AdminController::class, 'conditionValidationModal']],
    ['GET', '/admin/atestados/validacao/modal', [AdminController::class, 'healthCertificateValidationModal']],
    ['GET', '/api/admin/agenda/eventos', [AdminController::class, 'calendarEvents']],
    ['GET', '/admin/agendamentos/ocorrencia', [AdminController::class, 'bookingOccurrence']],
    ['GET', '/admin/horarios-semanais/detalhe', [AdminController::class, 'weeklyScheduleDetails']],
    ['GET', '/admin/agenda-horarios-especiais/detalhe', [AdminController::class, 'specialScheduleDetails']],
    ['POST', '/admin/pessoas/atualizar', [AdminController::class, 'updatePerson']],
    ['POST', '/admin/agendamentos/presenca', [AdminController::class, 'markBookingAttendance']],
    ['POST', '/admin/certificados/validacao/salvar', [AdminController::class, 'saveConditionValidation']],
    ['POST', '/admin/atestados/validacao/salvar', [AdminController::class, 'saveHealthCertificateValidation']],
    ['POST', '/admin/espacos/suspensoes', [AdminController::class, 'storeSpaceSuspension']],
    ['POST', '/admin/espacos/suspensoes/inativar', [AdminController::class, 'deactivateSpaceSuspension']],
    ['POST', '/admin/espacos/suspensoes/excluir', [AdminController::class, 'deleteFutureSpaceSuspension']],
    ['GET', '/admin/espacos/lista', [AdminController::class, 'trainingSpaceList']],
    ['POST', '/admin/espacos', [AdminController::class, 'storeTrainingSpace']],
    ['POST', '/admin/espacos/atualizar', [AdminController::class, 'updateTrainingSpace']],
    ['POST', '/admin/locais', [AdminController::class, 'storeTrainingLocation']],
    ['POST', '/admin/locais/atualizar', [AdminController::class, 'updateTrainingLocation']],
    ['GET', '/admin/locais/lista', [AdminController::class, 'trainingLocationList']],
    ['GET', '/admin/modalidades/lista', [AdminController::class, 'modalityList']],
    ['GET', '/admin/modalidades/detalhe', [AdminController::class, 'modalityDetails']],
    ['POST', '/admin/modalidades', [AdminController::class, 'storeModality']],
    ['POST', '/admin/modalidades/atualizar', [AdminController::class, 'updateModality']],
    ['GET', '/admin/migracao-locais/lista', [AdminController::class, 'externalTrainingLocations']],
    ['GET', '/admin/migracao-espacos/lista', [AdminController::class, 'externalTrainingSpaces']],
    ['POST', '/admin/horarios-semanais', [AdminController::class, 'storeWeeklySchedule']],
    ['POST', '/admin/horarios-semanais/atualizar', [AdminController::class, 'updateWeeklySchedule']],
    ['POST', '/admin/horarios-semanais/inativar', [AdminController::class, 'deactivateWeeklySchedule']],
    ['POST', '/admin/horarios-semanais/ativar', [AdminController::class, 'activateWeeklySchedule']],
    ['POST', '/admin/agenda-horarios-especiais', [AdminController::class, 'storeSpecialSchedule']],
    ['POST', '/admin/agenda-horarios-especiais/atualizar', [AdminController::class, 'updateSpecialSchedule']],
    ['POST', '/admin/agenda-horarios-especiais/inativar', [AdminController::class, 'deactivateSpecialSchedule']],
    ['POST', '/admin/home-info', [AdminController::class, 'saveHomeInfoBox']],
    ['POST', '/admin/home-destaques', [AdminController::class, 'saveHomeHighlightCards']],
    ['POST', '/admin/home-apresentacao', [AdminController::class, 'saveHomeHeroContent']],
    ['POST', '/admin/home-cabecalho', [AdminController::class, 'saveHomeHeaderContent']],
    ['POST', '/admin/home-logotipo', [AdminController::class, 'saveHomeLogoContent']],
    ['POST', '/admin/home-contato', [AdminController::class, 'saveHomeContactContent']],
    ['POST', '/admin/home-rodape', [AdminController::class, 'saveHomeFooterContent']],
    ['POST', '/admin/home-locais-cursos', [AdminController::class, 'saveHomeCoursesLocationsContent']],
    ['POST', '/admin/home-modalidades-cursos', [AdminController::class, 'saveHomeCourseModalitiesContent']],
    ['POST', '/admin/home-locais-treinos', [AdminController::class, 'saveHomeTrainingLocationsContent']],
    ['POST', '/admin/home-publicar', [AdminController::class, 'publishHomeContent']],
    ['POST', '/admin/comunicacao-oficial', [AdminController::class, 'saveOfficialCommunication']],
    ['POST', '/admin/comunicacao-oficial/publicar', [AdminController::class, 'publishOfficialCommunication']],
    ['POST', '/admin/postagens', [AdminController::class, 'storePost']],
    ['POST', '/admin/postagens/publicar', [AdminController::class, 'publishPost']],
    ['POST', '/admin/postagens/ativar', [AdminController::class, 'activatePost']],
    ['POST', '/admin/postagens/remover', [AdminController::class, 'deletePost']],
    ['POST', '/admin/site-popups', [AdminController::class, 'storeSitePopup']],
    ['POST', '/admin/site-popups/status', [AdminController::class, 'updateSitePopupStatus']],
    ['POST', '/admin/site-popups/remover', [AdminController::class, 'deleteSitePopup']],
    ['POST', '/admin/ceps-excecao', [AdminController::class, 'storeCepException']],
    ['POST', '/admin/ceps-excecao/remover', [AdminController::class, 'deleteCepException']],
    ['POST', '/admin/ceps-intervalo', [AdminController::class, 'storeAcceptedRange']],
    ['POST', '/admin/ceps-intervalo/remover', [AdminController::class, 'deleteAcceptedRange']],
    ['GET', '/professor', [ProfessorController::class, 'index']],
    ['GET', '/professor/secao', [ProfessorController::class, 'section']],
    ['GET', '/professor/pessoas/detalhe', [ProfessorController::class, 'personDetails']],
    ['GET', '/professor/pessoas/lista', [ProfessorController::class, 'peoplePanel']],
    ['GET', '/professor/usuarios/detalhe', [ProfessorController::class, 'userDetails']],
    ['GET', '/professor/usuarios/dependentes', [ProfessorController::class, 'userDependents']],
    ['GET', '/api/professor/agenda/eventos', [ProfessorController::class, 'calendarEvents']],
    ['GET', '/professor/agendamentos/ocorrencia', [ProfessorController::class, 'bookingOccurrence']],
    ['POST', '/professor/agendamentos/presenca', [ProfessorController::class, 'markBookingAttendance']],
    ['GET', '/professor/certificados/arquivo', [ProfessorController::class, 'certificateDocument']],
    ['GET', '/professor/certificados/validacao/modal', [ProfessorController::class, 'conditionValidationModal']],
    ['POST', '/professor/certificados/validacao/salvar', [ProfessorController::class, 'saveConditionValidation']],
    ['GET', '/professor/atestados/validacao/modal', [ProfessorController::class, 'healthCertificateValidationModal']],
    ['POST', '/professor/atestados/validacao/salvar', [ProfessorController::class, 'saveHealthCertificateValidation']],
];
