<?php if (($courseClasses ?? []) === []) { ?>
    <p class="muted">Selecione <?php echo ($courseManagementView ?? 'turmas') === 'turmas-locais' ? 'um local' : 'uma modalidade'; ?> para consultar as turmas.</p>
<?php } else { ?>
    <?php foreach ($courseClasses as $class) { ?>
        <article class="content-card professor-class-card admin-class-card" data-course-class-card="<?php echo e((string) $class['id']); ?>">
            <span class="eyebrow"><?php echo e((string) ($class['temporada_nome'] ?? '')); ?></span>
            <h3><span class="course-class-id">[<?php echo e((string) ($class['id'] ?? '')); ?>]</span> <?php echo e((string) ($class['nome'] ?? '')); ?></h3>
            <div class="professor-class-details">
                <p><strong>Modalidade:</strong> <?php echo e((string) ($class['modalidade_nome'] ?? '')); ?></p>
                <p><strong>Local:</strong> <?php echo e((string) ($class['local_nome'] ?? '')); ?>, <?php echo e((string) ($class['espaco_nome'] ?? '')); ?></p>
                <p><strong>Dias:</strong> <?php echo e((string) ($class['dias_semana_descricao'] ?? 'Não informado')); ?><?php if (!empty($class['hora_inicio']) && !empty($class['hora_fim'])) { echo e(', ' . substr((string) $class['hora_inicio'], 0, 5) . ' às ' . substr((string) $class['hora_fim'], 0, 5)); } ?></p>
                <p><strong><?php echo ($class['criterio_faixa_etaria'] ?? '') === 'ano_nascimento' ? 'Ano de nascimento' : 'Faixa etária'; ?>:</strong> <?php echo e((string) ($class['faixa_etaria_descricao'] ?? 'Não informada')); ?></p>
                <?php if (!empty($class['excecoes_idade_descricao'])) { ?><p><strong>Exceções de idade:</strong> <?php echo e(implode('; ', (array) $class['excecoes_idade_descricao'])); ?></p><?php } ?>
                <p><strong>Professor principal:</strong> <span data-course-class-main-professor-name><?php echo e((string) (($class['professor_principal_nome'] ?? '') ?: 'Sem professor principal')); ?></span></p>
                <p><strong>Status:</strong> <span class="class-status-badge class-status-<?php echo e((string) ($class['status'] ?? 'planejada')); ?>" data-course-class-status-label="1"><?php echo e((string) ($class['status_label'] ?? (!empty($class['ativo']) ? 'Planejada' : 'Inscrições suspensas'))); ?></span></p>
                <p><button type="button" class="course-class-details-link" data-course-class-details='<?php echo e((string) json_encode($class, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)); ?>'>Detalhes</button></p>
                <?php $totalClassEnrollments = (int) ($class['total_inscritos'] ?? 0); $totalEnrolledStudents = (int) ($class['total_matriculados'] ?? 0); ?>
                <p class="course-class-secondary-links"><button type="button" class="course-class-attendance-link" data-course-class-attendance='<?php echo e((string) json_encode($class, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)); ?>'>Fazer Chamada</button><button type="button" class="link-button course-class-enrollments-link" data-course-class-enrollments="<?php echo e((string) ($class['id'] ?? 0)); ?>" data-course-class-enrollments-name="<?php echo e((string) ($class['nome'] ?? '')); ?>">Consultar <?php echo e((string) $totalClassEnrollments); ?> <?php echo $totalClassEnrollments === 1 ? 'inscrito' : 'inscritos'; ?></button><a class="course-class-print-attendance-link" href="<?php echo e(url((($courseManagementView ?? '') === 'professor-turmas' ? '/professor/minhas-turmas/lista-chamada.pdf' : '/admin/turmas/lista-chamada.pdf') . '?turma_id=' . (int) ($class['id'] ?? 0))); ?>" target="_blank" rel="noopener">Imprimir lista de chamada [<?php echo e((string) $totalEnrolledStudents); ?>]</a><a class="course-class-address-list-link" href="<?php echo e(url((($courseManagementView ?? '') === 'professor-turmas' ? '/professor/minhas-turmas/lista-enderecos.pdf' : '/admin/turmas/lista-enderecos.pdf') . '?turma_id=' . (int) ($class['id'] ?? 0))); ?>" target="_blank" rel="noopener">Lista com endereços</a><button type="button" class="link-button course-class-tokens-link" data-course-class-tokens="<?php echo e((string) ($class['id'] ?? 0)); ?>" data-course-class-tokens-name="<?php echo e((string) ($class['nome'] ?? '')); ?>" data-course-class-tokens-scope="<?php echo ($courseManagementView ?? '') === 'professor-turmas' ? 'professor' : 'admin'; ?>">Tokens</button></p>
            </div>
            <div class="course-row-actions admin-class-card-actions">
                <button type="button" class="btn btn-primary" data-course-edit="class" data-course-record="<?php echo e((string) json_encode($class, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)); ?>">Editar</button>
                <?php if (($courseManagementView ?? 'turmas') !== 'professor-turmas') { ?><button type="button" class="btn btn-secondary" data-course-assign-professor="<?php echo e((string) $class['id']); ?>" data-course-main-professor="<?php echo e((string) ($class['professor_conta_id'] ?? '')); ?>" data-course-current-professors="<?php echo e((string) json_encode($class['professores_ids'] ?? [], JSON_UNESCAPED_UNICODE)); ?>" data-course-current-interns="<?php echo e((string) json_encode($class['estagiarios_ids'] ?? [], JSON_UNESCAPED_UNICODE)); ?>">Equipe</button><?php } ?>
                <button type="button" class="btn btn-secondary" data-course-class-status-open="1" data-course-class-id="<?php echo e((string) $class['id']); ?>" data-course-class-name="<?php echo e((string) ($class['nome'] ?? '')); ?>" data-course-class-status="<?php echo e((string) ($class['status'] ?? 'planejada')); ?>" data-course-class-schedule-status="<?php echo e((string) ($class['status_cronograma'] ?? 'planejada')); ?>" data-course-management-view="<?php echo e((string) $courseManagementView); ?>">Alterar status</button>
                <button type="button" class="btn btn-danger" data-course-class-delete="<?php echo e((string) $class['id']); ?>" data-course-class-name="<?php echo e((string) ($class['nome'] ?? '')); ?>">Excluir</button>
            </div>
        </article>
    <?php } ?>
<?php } ?>
<div class="popup-overlay hidden" id="course-class-details-modal" aria-hidden="true"><div class="popup-card" role="dialog" aria-modal="true" aria-labelledby="course-class-details-title"><div class="popup-head"><div><h3 id="course-class-details-title">Detalhes da turma</h3><p class="muted" data-course-details-subtitle></p></div><button type="button" class="popup-close-icon" data-course-details-close="1" aria-label="Fechar">&times;</button></div><div class="popup-body"><div class="course-class-details-modal-content" data-course-details-content></div><div class="popup-actions"><button type="button" class="btn btn-secondary" data-course-details-close="1">Fechar</button></div></div></div></div>
<div class="popup-overlay hidden" id="course-class-attendance-modal" aria-hidden="true"><div class="popup-card popup-admin-card class-attendance-modal-card" role="dialog" aria-modal="true"><div class="popup-head"><div><h3>Fazer chamada</h3><p class="muted" data-class-attendance-subtitle></p></div><button type="button" class="popup-close-icon" data-class-attendance-close="1" aria-label="Fechar">&times;</button></div><div class="popup-body"><div id="course-class-attendance-calendar"></div></div></div></div>
<div class="popup-overlay hidden class-attendance-roster-modal" id="course-class-attendance-roster-modal" aria-hidden="true"><div class="popup-card popup-admin-card class-attendance-roster-modal-card" role="dialog" aria-modal="true" aria-labelledby="class-attendance-roster-title"><div class="popup-head"><div><h3 id="class-attendance-roster-title">Lista para fazer chamada</h3><p class="muted">Registre a presença dos alunos na data selecionada.</p></div><button type="button" class="popup-close-icon" data-class-attendance-roster-close="1" aria-label="Fechar">&times;</button></div><div class="popup-body"><div class="class-attendance-roster" data-class-attendance-roster></div></div></div></div>
<div class="popup-overlay hidden" id="admin-health-certificate-validation-modal" aria-hidden="true"><div class="popup-card popup-admin-card admin-condition-validation-card" role="dialog" aria-modal="true" aria-labelledby="admin-health-certificate-validation-title"><div id="admin-health-certificate-validation-modal-content"></div></div></div>
<div class="popup-overlay hidden" id="course-class-justification-modal" aria-hidden="true"><div class="popup-card popup-admin-card class-justification-modal-card" role="dialog" aria-modal="true" aria-labelledby="course-class-justification-title"><div class="popup-head"><div><h3 id="course-class-justification-title">Justificar ausência</h3><p class="muted" data-class-justification-person></p></div><button type="button" class="popup-close-icon" data-class-justification-close="1" aria-label="Fechar">&times;</button></div><form class="popup-body stack-form" data-class-justification-form="1"><label><span>Motivo da justificativa</span><select data-justification-reason-select required></select></label><label class="hidden" data-justification-other-wrap><span>Descreva o outro motivo</span><input type="text" data-justification-other maxlength="255"></label><div class="admin-weekly-schedule-actions"><button type="button" class="btn btn-secondary" data-class-justification-close="1">Cancelar</button><button type="submit" class="btn btn-primary">Salvar justificativa</button></div></form></div></div>
<div class="popup-overlay hidden" id="class-enrollment-action-modal" aria-hidden="true"><div class="popup-card popup-admin-card class-justification-modal-card" role="dialog" aria-modal="true"><div class="popup-head"><h3>Confirmar alteração da matrícula</h3><button type="button" class="popup-close-icon" data-class-enrollment-action-close="1" aria-label="Fechar">&times;</button></div><div class="popup-body"><p data-class-enrollment-action-question></p><div class="popup-actions"><button type="button" class="btn btn-secondary" data-class-enrollment-action-close="1">Cancelar</button><button type="button" class="btn btn-primary" data-class-enrollment-action-confirm="1">Confirmar</button></div></div></div></div>
