<?php
$class = (array) ($attendance['class'] ?? []); $students = (array) ($attendance['students'] ?? []);
$activeStudents = array_values(array_filter($students, static fn(array $r): bool => ($r['matricula_status'] ?? '') === 'matriculada'));
$suspendedStudents = array_values(array_filter($students, static fn(array $r): bool => ($r['matricula_status'] ?? '') === 'suspensa'));
$today = new DateTimeImmutable('today'); $warningLimit = $today->modify('+30 days');
$certificateState = static function ($id, $validity) use ($today, $warningLimit): string { if (empty($id)) return 'none'; if (empty($validity)) return 'valid'; $date = new DateTimeImmutable((string)$validity); return $date < $today ? 'expired' : ($date <= $warningLimit ? 'warning' : 'valid'); };
$stateColor = ['none'=>'#fff','valid'=>'#ddf7df','warning'=>'#fff0d5','expired'=>'#fde0e0'];
$documentBase = !empty($professorView) ? '/professor/atestados/arquivo' : '/admin/atestados/arquivo';
$renderCertificate = static function(array $student, string $type, string $label) use ($certificateState, $documentBase): void {
    $validatedId=$student['atestado_'.$type.'_validado_id']??null; $fileId=$student['atestado_'.$type.'_arquivo_id']??null; $state=$certificateState($validatedId,$student['atestado_'.$type.'_validade']??null);
    if ($fileId) { ?><a class="class-attendance-pdf" href="<?php echo e(url($documentBase.'?certificate_id='.(int)$fileId)); ?>" target="_blank" rel="noopener" title="Abrir PDF" aria-label="Abrir PDF do atestado">PDF</a><?php }
    ?><button type="button" class="link-button class-attendance-certificate-name is-<?php echo e($state); ?>" data-open-health-certificate-validation="1" data-person-id="<?php echo e((string)$student['pessoa_id']); ?>" data-certificate-type="<?php echo e($type); ?>"><?php echo $validatedId ? e($label) : '['.e($label).']'; ?></button><?php
    if ($state==='expired') { ?><span class="class-certificate-state is-expired" title="Atestado vencido">?</span><?php } elseif ($state==='warning') { ?><span class="class-certificate-state is-warning" title="Atestado a vencer">▲</span><?php } elseif ($state==='valid') { ?><span class="class-certificate-state is-valid" title="Atestado em vigor">✓</span><?php }
};
?>
<div class="class-attendance-heading" data-class-attendance-date="<?php echo e((string)$attendance['date']); ?>"><h3>[<?php echo e((string)($class['id']??'')); ?>] <?php echo e((string)($class['nome']??'Turma')); ?></h3><p><strong><?php echo e((new DateTimeImmutable((string)$attendance['date']))->format('d/m/Y')); ?></strong> · <?php echo e((string)($class['dias_semana_descricao']??'')); ?><?php if (!empty($class['hora_inicio'])) { ?>, <?php echo e(substr((string)$class['hora_inicio'],0,5)); ?> às <?php echo e(substr((string)$class['hora_fim'],0,5)); ?><?php } ?></p></div>
<?php if ($activeStudents===[]) { ?><p class="muted">Nenhum aluno com matrícula ativa nesta turma.</p><?php } else { ?><div class="class-attendance-list"><?php foreach($activeStudents as $student) { $status=(string)($student['chamada_status']??''); $cs=$certificateState($student['atestado_clinico_validado_id']??null,$student['atestado_clinico_validade']??null); $ds=$certificateState($student['atestado_dermatologico_validado_id']??null,$student['atestado_dermatologico_validade']??null); $bg='linear-gradient(90deg,'.$stateColor[$cs].' 0%,'.$stateColor[$cs].' 44%,'.$stateColor[$ds].' 56%,'.$stateColor[$ds].' 100%)'; ?>
<article class="class-attendance-student" style="background:<?php echo e($bg); ?>" data-class-attendance-row="<?php echo e((string)$student['inscricao_id']); ?>"><div class="class-attendance-student-head"><span class="class-attendance-mark is-<?php echo e($status?:'pending'); ?>" data-class-attendance-mark><?php echo ['presente'=>'✓','ausente'=>'×','justificado'=>'J'][$status]??'−'; ?></span><strong><?php echo e((string)$student['nome_completo']); ?></strong><button type="button" class="link-button class-enrollment-action" data-class-enrollment-action="suspensa" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Suspender matrícula</button></div>
<div class="class-attendance-certificates"><span><?php $renderCertificate($student,'clinico','Clínico'); ?></span><span><?php $renderCertificate($student,'dermatologico','Dermatológico'); ?></span></div><div class="class-attendance-options"><?php foreach(['presente'=>'Presente','ausente'=>'Ausente','justificado'=>'Justificar'] as $value=>$label) { ?><label class="class-attendance-<?php echo e($value); ?>"><input type="checkbox" data-class-attendance-status="<?php echo e($value); ?>" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>" data-birth-date="<?php echo e((string)($student['data_nascimento']??'')); ?>" data-current-justification="<?php echo e((string)($student['justificativa']??'')); ?>" <?php echo $status===$value?'checked':''; ?>> <?php echo e($label); ?></label><?php } ?></div></article><?php } ?></div><?php } ?>
<?php if ($suspendedStudents!==[]) { ?><section class="class-attendance-suspended"><h3>Matrículas suspensas</h3><?php foreach($suspendedStudents as $student) { ?><div><strong><?php echo e((string)$student['nome_completo']); ?></strong><span><button type="button" class="link-button class-enrollment-action" data-class-enrollment-action="matriculada" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Rematricular</button> <button type="button" class="link-button class-enrollment-action is-danger" data-class-enrollment-action="desistente" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Marcar como desistente</button></span></div><?php } ?></section><?php } ?>
