<?php
$courseEnrollmentsManagement = $courseEnrollmentsManagement ?? [];
$enrollmentsByPerson = [];
foreach ($courseEnrollmentsManagement as $item) {
    $enrollmentsByPerson[(int) ($item['pessoa_id'] ?? 0)][] = [
        'id' => (int) ($item['id'] ?? 0), 'turma' => (string) ($item['turma_nome'] ?? ''),
        'temporada' => (string) ($item['temporada_nome'] ?? ''), 'status' => (string) ($item['status_label'] ?? ''),
        'data' => !empty($item['created_at']) ? date('d/m/Y H:i', strtotime((string) $item['created_at'])) : '-',
    ];
}
$jsonAttribute = static fn (array $value): string => e((string) json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
$formatDate = static fn ($value, bool $withTime = false): string => !empty($value) ? date($withTime ? 'd/m/Y H:i' : 'd/m/Y', strtotime((string) $value)) : ($withTime ? '-' : '00/00/0000');
?>
<section class="admin-section-panel course-enrollment-management" data-admin-section="inscricoes">
    <div class="section-head admin-section-head"><div><h2>Inscrições em cursos</h2><p class="muted">Consulte os dados, o histórico e altere a situação de cada inscrição.</p></div></div>
    <?php if ($courseEnrollmentsManagement === []) { ?><p class="muted">Nenhuma inscrição pendente, matriculada ou suspensa.</p><?php } else { ?>
        <div class="course-enrollment-list">
        <?php foreach ($courseEnrollmentsManagement as $enrollment) {
            $whatsapp = preg_replace('/\\D+/', '', (string) (($enrollment['responsavel_whatsapp'] ?? '') ?: ($enrollment['telefone_whatsapp'] ?? ''))) ?? '';
            if ($whatsapp !== '' && !str_starts_with($whatsapp, '55')) { $whatsapp = '55' . $whatsapp; }
            $address = ['logradouro' => trim((string) ($enrollment['logradouro'] ?? '')), 'numero' => trim((string) ($enrollment['numero_endereco'] ?? '')), 'complemento' => trim((string) ($enrollment['complemento'] ?? '')), 'bairro' => trim((string) ($enrollment['bairro'] ?? '')), 'cidade' => trim((string) ($enrollment['cidade'] ?? '')), 'uf' => trim((string) ($enrollment['uf'] ?? '')), 'cep' => trim((string) ($enrollment['cep'] ?? '')), 'telefone' => trim((string) ($enrollment['telefone_whatsapp'] ?? '')), 'emergencia_nome' => trim((string) ($enrollment['contato_emergencia_nome'] ?? '')), 'emergencia_telefone' => trim((string) ($enrollment['contato_emergencia_telefone'] ?? ''))];
            $details = ['id' => (int) $enrollment['id'], 'nome' => (string) $enrollment['nome_completo'], 'idade' => $enrollment['idade'], 'turma' => (string) $enrollment['turma_nome'], 'temporada' => (string) $enrollment['temporada_nome'], 'horario' => trim((string) ($enrollment['dias_semana_descricao'] ?? '')) . (!empty($enrollment['hora_inicio']) ? ', das ' . substr((string) $enrollment['hora_inicio'], 0, 5) . ' às ' . substr((string) $enrollment['hora_fim'], 0, 5) : ''), 'local' => (string) $enrollment['local_nome'] . ' — ' . (string) $enrollment['espaco_nome'], 'data_inscricao' => $formatDate($enrollment['created_at'] ?? null, true), 'com_laudo' => (int) ($enrollment['possui_laudo'] ?? 0) > 0 ? 'Sim' : 'Não', 'pcd' => (int) ($enrollment['eh_pcd'] ?? 0) === 1 ? 'Sim' : 'Não', 'responsavel' => trim((string) ($enrollment['responsavel_nome'] ?? '')), 'responsavel_email' => trim((string) ($enrollment['responsavel_email'] ?? '')), 'status' => (string) $enrollment['status_label'], 'aulas_inicio' => $formatDate($enrollment['aulas_inicio'] ?? null), 'outras_inscricoes' => $enrollmentsByPerson[(int) $enrollment['pessoa_id']] ?? []];
            $clinicalExpired = !empty($enrollment['atestado_clinico_validade']) && strtotime((string) $enrollment['atestado_clinico_validade']) < strtotime(date('Y-m-d'));
            $dermExpired = !empty($enrollment['atestado_dermatologico_validade']) && strtotime((string) $enrollment['atestado_dermatologico_validade']) < strtotime(date('Y-m-d'));
        ?>
            <article class="course-enrollment-row">
                <div class="course-enrollment-person">
                    <p><strong><?php echo e((string) ($enrollment['numero_ordem'] ?? '-')); ?>º</strong> · <strong>[<?php echo e((string) $enrollment['id']); ?>]</strong> · <strong><?php echo e((string) $enrollment['nome_completo']); ?></strong> · <?php echo e(format_cpf_professor((string) $enrollment['cpf'])); ?><?php if ($enrollment['idade'] !== null) { ?> · <strong><?php echo e((string) $enrollment['idade']); ?> anos</strong><?php } ?><?php if (!empty($enrollment['data_nascimento'])) { ?> · Nascim.: <?php echo e($formatDate($enrollment['data_nascimento'])); ?><?php } ?></p>
                    <p><?php if ((int) ($enrollment['eh_pvs'] ?? 0) === 1 && trim((string) ($enrollment['numero_nis'] ?? '')) !== '') { ?><strong>Número do CadÚnico (NIS):</strong> <?php echo e((string) $enrollment['numero_nis']); ?> · <?php } ?><a href="#" class="course-future-link" data-future-label="PAR-Q">PAR-Q</a><?php if (!empty($enrollment['responsavel_nome'])) { ?> · <strong>Resp.:</strong> <?php echo e((string) $enrollment['responsavel_nome']); ?><?php } ?><?php if ($whatsapp !== '') { ?> · <a href="https://wa.me/<?php echo e($whatsapp); ?>" target="_blank" rel="noopener">WhatsApp: <?php echo e((string) (($enrollment['responsavel_whatsapp'] ?? '') ?: $enrollment['telefone_whatsapp'])); ?></a><?php } ?> · <button type="button" class="link-button course-address-open" data-address="<?php echo $jsonAttribute($address); ?>">Endereço</button></p>
                    <p><strong>Dt. Insc.:</strong> <?php echo e($formatDate($enrollment['created_at'] ?? null)); ?> · <strong>Dt. Matric.:</strong> <?php echo e($formatDate($enrollment['data_matricula'] ?? null)); ?></p>
                    <p class="course-certificate-line"><strong>Atestados:</strong>
                        <?php if (!empty($enrollment['atestado_clinico_id'])) { ?><a class="certificate-present" href="<?php echo e(url('/professor/atestados/arquivo?certificate_id=' . (int) $enrollment['atestado_clinico_id'])); ?>" target="_blank" rel="noopener" title="Abrir atestado clínico">▧ Clínico</a><?php if ($clinicalExpired) { ?> <span class="certificate-expired" title="Atestado clínico vencido">?</span><?php } ?><?php } else { ?><span class="certificate-missing">[Clínico]</span><?php } ?>
                        <?php if (!empty($enrollment['atestado_dermatologico_id'])) { ?><a class="certificate-present" href="<?php echo e(url('/professor/atestados/arquivo?certificate_id=' . (int) $enrollment['atestado_dermatologico_id'])); ?>" target="_blank" rel="noopener" title="Abrir atestado dermatológico">▧ Dermatológico</a><?php if ($dermExpired) { ?> <span class="certificate-expired" title="Atestado dermatológico vencido">?</span><?php } ?><?php } else { ?><span class="certificate-missing">[Dermatológico]</span><?php } ?>
                        <?php if (trim((string) ($enrollment['condicoes'] ?? '')) !== '') { ?> · <span class="course-special-condition"><?php echo e((string) $enrollment['condicoes']); ?></span><?php } ?>
                    </p>
                </div>
                <div class="course-enrollment-context"><strong><?php echo e((string) $enrollment['turma_nome']); ?></strong><small><?php echo e((string) $enrollment['modalidade_nome']); ?> · <?php echo e((string) $enrollment['temporada_nome']); ?></small></div>
                <div class="course-enrollment-links"><button type="button" class="course-status-history-open status-highlight" data-history="<?php echo $jsonAttribute((array) ($enrollment['historico'] ?? [])); ?>" data-enrollment-number="<?php echo e((string) $enrollment['id']); ?>"><?php echo e((string) $enrollment['status_label']); ?></button><button type="button" class="link-button course-enrollment-details-open" data-details="<?php echo $jsonAttribute($details); ?>">Detalhes</button></div>
                <form method="POST" action="<?php echo e(url('/professor/inscricoes/status')); ?>" class="stack-form course-enrollment-status-form" data-ajax-form="1" data-follow-redirect="1"><input type="hidden" name="inscricao_id" value="<?php echo e((string) $enrollment['id']); ?>"><select name="status" required><option value="">Novo status</option><option value="matriculada">Matriculada</option><option value="suspensa">Suspensa</option><option value="excluida">Excluída</option><option value="excluida_por_falta">Excluída por falta</option><option value="desistente">Desistente</option></select><input type="datetime-local" value="<?php echo e(date('Y-m-d\\TH:i')); ?>" readonly aria-label="Data e hora da alteração" title="A data e a hora reais da alteração serão armazenadas automaticamente"><input type="text" name="motivo" placeholder="Motivo (opcional)"><button type="submit" class="btn btn-primary">Salvar</button></form>
            </article>
        <?php } ?>
        </div>
    <?php } ?>
</section>
<div id="course-enrollment-info-modal" class="popup-overlay hidden" aria-hidden="true"><div class="popup-card course-enrollment-info-card" role="dialog" aria-modal="true" aria-labelledby="course-enrollment-info-title"><div class="popup-head"><h3 id="course-enrollment-info-title">Informações da inscrição</h3><button type="button" class="popup-close-icon" data-course-enrollment-modal-close="1" aria-label="Fechar">×</button></div><div id="course-enrollment-info-body" class="popup-body"></div><div class="popup-actions"><button type="button" class="btn btn-secondary" data-course-enrollment-modal-close="1">Fechar</button></div></div></div>
