<?php
$class = (array) ($attendance['class'] ?? []); $students = (array) ($attendance['students'] ?? []);
$activeStudents = array_values(array_filter($students, static fn(array $r): bool => ($r['matricula_status'] ?? '') === 'matriculada'));
$suspendedStudents = array_values(array_filter($students, static fn(array $r): bool => ($r['matricula_status'] ?? '') === 'suspensa'));
$absenceExcludedStudents = array_values(array_filter($students, static fn(array $r): bool => ($r['matricula_status'] ?? '') === 'excluida_por_falta'));
$today = new DateTimeImmutable('today'); $warningLimit = $today->modify('+30 days');
$certificateState = static function ($id, $validity, string $status = 'validado') use ($today, $warningLimit): string { if (empty($id) || $status !== 'validado') return 'none'; if (empty($validity)) return 'valid'; $date = new DateTimeImmutable((string)$validity); return $date < $today ? 'expired' : ($date <= $warningLimit ? 'warning' : 'valid'); };
$stateColor = ['none'=>'#fff','valid'=>'#ddf7df','warning'=>'#fff0d5','expired'=>'#fde0e0'];
$documentBase = !empty($professorView) ? '/professor/atestados/arquivo' : '/admin/atestados/arquivo';
$renderCertificate = static function(array $student, string $type, string $label) use ($certificateState, $documentBase): void {
    $certificateId=$student['atestado_'.$type.'_validado_id']??null; $fileId=$student['atestado_'.$type.'_arquivo_id']??null; $origin=(string)($student['atestado_'.$type.'_origem']??''); $status=(string)($student['atestado_'.$type.'_status']??''); $validity=trim((string)($student['atestado_'.$type.'_validade']??'')); $state=$certificateState($certificateId,$validity,$status);
    if ($origin!=='importado') {
        $shortLabel=str_replace('Atestado ','',$label);
        if ($fileId) { ?><a class="class-attendance-pdf" href="<?php echo e(url($documentBase.'?certificate_id='.(int)$fileId)); ?>" target="_blank" rel="noopener" title="Abrir PDF" aria-label="Abrir PDF do atestado">PDF</a><?php }
        ?><button type="button" class="link-button class-attendance-certificate-name is-<?php echo e($state); ?>" <?php if ($fileId) { ?>data-open-health-certificate-validation="1"<?php } else { ?>data-missing-health-certificate="1" data-certificate-label="<?php echo e(mb_strtolower($shortLabel,'UTF-8')); ?>"<?php } ?> data-person-id="<?php echo e((string)$student['pessoa_id']); ?>" data-certificate-type="<?php echo e($type); ?>"><?php echo $status==='validado'?e($shortLabel):'['.e($shortLabel).']'; ?><?php if ($state==='expired') { ?><span class="class-certificate-state is-expired" title="Atestado vencido">?</span><?php } elseif ($state==='warning') { ?><span class="class-certificate-state is-warning" title="Atestado a vencer">▲</span><?php } elseif ($state==='valid') { ?><span class="class-certificate-state is-valid" title="Atestado em vigor">✓</span><?php } ?></button><?php
        return;
    }
    $statusLabel=$origin===''?'Não enviado':($status==='validado'?'Validado':($status==='reprovado'?'Reprovado':'Pendente')); $icon=''; $iconClass=''; $message='';
    if ($state==='expired') { $statusLabel='Vencido'; $icon='!'; $iconClass='is-expired'; $message=$label.' vencido'.($validity!==''?' em '.(new DateTimeImmutable($validity))->format('d/m/Y'):'').'.'; }
    elseif ($state==='warning') { $statusLabel='A vencer'; $icon='!'; $iconClass='is-warning'; $message=$label.' vence em '.(new DateTimeImmutable($validity))->format('d/m/Y').'.'; }
    elseif ($state==='valid') { $icon='OK'; $iconClass='is-ok'; $message=$label.' validado'.($validity!==''?' até '.(new DateTimeImmutable($validity))->format('d/m/Y'):'').'.'; }
    elseif ($status==='reprovado') { $icon='!'; $iconClass='is-expired'; $message=$label.' reprovado e aguardando regularização.'; }
    elseif ($status!=='') { $icon='!'; $iconClass='is-warning'; $message=$label.' aguardando validação administrativa.'; }
    ?><span class="health-certificate-summary"><span class="health-certificate-summary-text"><strong><?php echo e($label); ?></strong><small><span class="muted">(importado)</span> <span class="muted"><?php echo e($statusLabel); ?></span><?php if ($icon!=='') { ?> <button type="button" class="admin-status-icon-button <?php echo e($iconClass); ?>" data-certificate-status-alert="1" data-alert-level="erro" data-alert-message="<?php echo e($message); ?>" title="<?php echo e($message); ?>"><?php if ($iconClass==='is-expired') { ?><span class="admin-status-icon-circle">!</span><?php } elseif ($iconClass==='is-warning') { ?><span class="admin-status-icon-triangle">!</span><?php } else { ?><span class="admin-status-icon-ok">OK</span><?php } ?></button><?php } ?></small></span></span><?php
};
?>
<div class="class-attendance-heading" data-class-attendance-date="<?php echo e((string)$attendance['date']); ?>"><h3>[<?php echo e((string)($class['id']??'')); ?>] <?php echo e((string)($class['nome']??'Turma')); ?></h3><p><strong><?php echo e((new DateTimeImmutable((string)$attendance['date']))->format('d/m/Y')); ?></strong> · <?php echo e((string)($class['dias_semana_descricao']??'')); ?><?php if (!empty($class['hora_inicio'])) { ?>, <?php echo e(substr((string)$class['hora_inicio'],0,5)); ?> às <?php echo e(substr((string)$class['hora_fim'],0,5)); ?><?php } ?></p></div>
<?php if ($activeStudents===[]) { ?><p class="muted">Nenhum aluno com matrícula ativa nesta turma.</p><?php } else { ?><div class="class-attendance-list"><?php foreach($activeStudents as $student) { $status=(string)($student['chamada_status']??''); $cs=$certificateState($student['atestado_clinico_validado_id']??null,$student['atestado_clinico_validade']??null,(string)($student['atestado_clinico_status']??'')); $ds=$certificateState($student['atestado_dermatologico_validado_id']??null,$student['atestado_dermatologico_validade']??null,(string)($student['atestado_dermatologico_status']??'')); $bg='linear-gradient(90deg,'.$stateColor[$cs].' 0%,'.$stateColor[$cs].' 44%,'.$stateColor[$ds].' 56%,'.$stateColor[$ds].' 100%)'; ?>
<article class="class-attendance-student" style="background:<?php echo e($bg); ?>" data-class-attendance-row="<?php echo e((string)$student['inscricao_id']); ?>"><div class="class-attendance-student-head"><span class="class-attendance-mark is-<?php echo e($status?:'pending'); ?>" data-class-attendance-mark><?php echo ['presente'=>'✓','ausente'=>'×','justificado'=>'J'][$status]??'−'; ?></span><strong><?php echo e((string)$student['nome_completo']); ?></strong><button type="button" class="link-button class-enrollment-action" data-class-enrollment-action="suspensa" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Suspender matrícula</button></div>
<div class="class-attendance-certificates"><span><?php $renderCertificate($student,'clinico','Atestado clínico'); ?></span><span><?php $renderCertificate($student,'dermatologico','Atestado dermatológico'); ?></span></div><div class="class-attendance-options"><?php foreach(['presente'=>'Presente','ausente'=>'Ausente','justificado'=>'Justificar'] as $value=>$label) { ?><label class="class-attendance-<?php echo e($value); ?>"><input type="checkbox" data-class-attendance-status="<?php echo e($value); ?>" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>" data-birth-date="<?php echo e((string)($student['data_nascimento']??'')); ?>" data-current-justification="<?php echo e((string)($student['justificativa']??'')); ?>" <?php echo $status===$value?'checked':''; ?>> <?php echo e($label); ?></label><?php } ?></div></article><?php } ?></div><?php } ?>
<?php if ($suspendedStudents!==[]) { ?><section class="class-attendance-suspended"><h3>Matrículas suspensas</h3><?php foreach($suspendedStudents as $student) { ?><div><strong><?php echo e((string)$student['nome_completo']); ?></strong><span><button type="button" class="link-button class-enrollment-action" data-class-enrollment-action="matriculada" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Rematricular</button> <button type="button" class="link-button class-enrollment-action is-danger" data-class-enrollment-action="desistente" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Marcar como desistente</button></span></div><?php } ?></section><?php } ?>
<?php if ($absenceExcludedStudents!==[]) { ?><section class="class-attendance-suspended class-attendance-absence-excluded"><h3>Matrículas excluídas por falta</h3><?php foreach($absenceExcludedStudents as $student) { ?><div><span><strong><?php echo e((string)$student['nome_completo']); ?></strong><small>Excluída por falta</small></span><button type="button" class="link-button class-enrollment-action" data-class-enrollment-action="matriculada" data-enrollment-id="<?php echo e((string)$student['inscricao_id']); ?>" data-person-name="<?php echo e((string)$student['nome_completo']); ?>">Rematricular</button></div><?php } ?></section><?php } ?>
